# Generated by Django 6.0.4 on 2026-04-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_renewalreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
