# Generated by Django 6.0.4 on 2026-04-28 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenewalReminder',
        ),
    ]
