# Generated by Django 6.0.4 on 2026-04-29 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('invoices', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.payment'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('customer_created', 'Customer Created'), ('customer_updated', 'Customer Updated'), ('customer_deleted', 'Customer Deleted'), ('policy_created', 'Policy Created'), ('policy_updated', 'Policy Updated'), ('policy_deleted', 'Policy Deleted'), ('invoice_created', 'Invoice Created'), ('invoice_updated', 'Invoice Updated'), ('invoice_deleted', 'Invoice Deleted'), ('payment_created', 'Payment Created'), ('payment_updated', 'Payment Updated'), ('payment_deleted', 'Payment Deleted')], max_length=50),
        ),
    ]
