# Generated by Django 6.0.4 on 2026-04-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
    ]
