# Generated by Django 6.0.4 on 2026-04-30 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activitylog_payment'),
        ('invoices', '0003_remove_payment_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
